"""
Bảng dịch Trung – Việt cho từ vựng HSK 1-6.
Key = chữ giản thể, Value = nghĩa tiếng Việt.
"""

VI = {
    # ═══════════════ HSK 1 ═══════════════
    "爱": "yêu, thương",
    "八": "tám",
    "爸爸": "bố, ba",
    "杯子": "cái cốc, cái ly",
    "北京": "Bắc Kinh",
    "本": "quyển, cuốn (lượng từ)",
    "不客气": "không có gì, không có chi",
    "不": "không",
    "菜": "rau, món ăn",
    "茶": "trà",
    "吃": "ăn",
    "出租车": "xe taxi",
    "打电话": "gọi điện thoại",
    "大": "to, lớn",
    "的": "của (trợ từ)",
    "点": "giờ, điểm",
    "电脑": "máy tính",
    "电视": "tivi",
    "电影": "phim, điện ảnh",
    "东西": "đồ vật, đồ đạc",
    "都": "đều, tất cả",
    "读": "đọc",
    "对不起": "xin lỗi",
    "多": "nhiều",
    "多少": "bao nhiêu",
    "儿子": "con trai",
    "二": "hai",
    "饭店": "nhà hàng, khách sạn",
    "飞机": "máy bay",
    "分钟": "phút",
    "高兴": "vui vẻ, vui mừng",
    "个": "cái (lượng từ)",
    "工作": "làm việc, công việc",
    "狗": "chó",
    "汉语": "tiếng Hán, tiếng Trung",
    "好": "tốt, được",
    "喝": "uống",
    "和": "và, với",
    "很": "rất",
    "后面": "phía sau, đằng sau",
    "回": "về, quay về",
    "会": "biết, sẽ",
    "火车站": "ga tàu hỏa",
    "几": "mấy, bao nhiêu",
    "家": "nhà, gia đình",
    "叫": "gọi, tên là",
    "今天": "hôm nay",
    "九": "chín",
    "开": "mở, lái",
    "看": "nhìn, xem",
    "看见": "nhìn thấy, trông thấy",
    "块": "đồng, tệ (đơn vị tiền)",
    "来": "đến, lại",
    "老师": "giáo viên, thầy/cô",
    "了": "rồi (trợ từ)",
    "冷": "lạnh",
    "里": "trong, bên trong",
    "零": "không, số 0",
    "六": "sáu",
    "妈妈": "mẹ, má",
    "吗": "không? (trợ từ nghi vấn)",
    "买": "mua",
    "猫": "mèo",
    "没关系": "không sao, không có gì",
    "没有": "không có",
    "米饭": "cơm",
    "名字": "tên",
    "明天": "ngày mai",
    "哪": "nào, đâu",
    "那": "đó, kia",
    "呢": "đây? (trợ từ)",
    "能": "có thể",
    "你": "bạn, anh/chị",
    "年": "năm",
    "女儿": "con gái",
    "朋友": "bạn bè",
    "漂亮": "đẹp, xinh đẹp",
    "苹果": "quả táo",
    "七": "bảy",
    "前面": "phía trước, đằng trước",
    "钱": "tiền",
    "请": "mời, xin",
    "去": "đi",
    "热": "nóng",
    "人": "người",
    "认识": "quen biết, nhận ra",
    "三": "ba",
    "商店": "cửa hàng",
    "上": "trên, lên",
    "上午": "buổi sáng",
    "少": "ít",
    "谁": "ai",
    "什么": "cái gì, gì",
    "十": "mười",
    "时候": "lúc, khi",
    "是": "là",
    "书": "sách",
    "水": "nước",
    "水果": "trái cây, hoa quả",
    "睡觉": "ngủ",
    "说": "nói",
    "四": "bốn",
    "岁": "tuổi",
    "他": "anh ấy, ông ấy",
    "她": "cô ấy, bà ấy",
    "太": "quá",
    "天气": "thời tiết",
    "听": "nghe",
    "同学": "bạn cùng lớp",
    "喂": "alo, này (thán từ)",
    "我": "tôi",
    "我们": "chúng tôi, chúng ta",
    "五": "năm",
    "喜欢": "thích",
    "下": "dưới, xuống",
    "下午": "buổi chiều",
    "下雨": "mưa",
    "先生": "ông, ngài",
    "现在": "bây giờ, hiện tại",
    "想": "muốn, nghĩ",
    "小": "nhỏ, bé",
    "小姐": "cô, tiểu thư",
    "些": "một số, vài",
    "写": "viết",
    "谢谢": "cảm ơn",
    "星期": "tuần, thứ",
    "学生": "học sinh, sinh viên",
    "学习": "học tập",
    "学校": "trường học",
    "一": "một",
    "衣服": "quần áo",
    "医生": "bác sĩ",
    "医院": "bệnh viện",
    "椅子": "ghế",
    "有": "có",
    "月": "tháng, trăng",
    "再见": "tạm biệt",
    "在": "ở, đang",
    "怎么": "thế nào, sao",
    "怎么样": "thế nào, ra sao",
    "这": "đây, này",
    "中国": "Trung Quốc",
    "中午": "buổi trưa",
    "住": "ở, sống",
    "桌子": "cái bàn",
    "字": "chữ",
    "昨天": "hôm qua",
    "坐": "ngồi, đi (xe)",
    "做": "làm",

    # ═══════════════ HSK 2 ═══════════════
    "吧": "đi, nhé (trợ từ)",
    "白": "trắng",
    "百": "trăm",
    "帮助": "giúp đỡ",
    "报纸": "báo, tờ báo",
    "比": "so với",
    "别": "đừng, chớ",
    "宾馆": "khách sạn",
    "长": "dài",
    "唱歌": "hát, ca hát",
    "出": "ra",
    "穿": "mặc, mang",
    "船": "tàu, thuyền",
    "次": "lần",
    "从": "từ",
    "错": "sai, lỗi",
    "打篮球": "chơi bóng rổ",
    "大家": "mọi người",
    "到": "đến, tới",
    "得": "được (trợ từ bổ ngữ)",
    "等": "đợi, chờ",
    "弟弟": "em trai",
    "第一": "thứ nhất",
    "懂": "hiểu",
    "对": "đúng, đối với",
    "房间": "phòng",
    "非常": "rất, vô cùng",
    "服务员": "nhân viên phục vụ",
    "高": "cao",
    "告诉": "nói cho biết, báo",
    "哥哥": "anh trai",
    "给": "cho, đưa",
    "公共汽车": "xe buýt",
    "公司": "công ty",
    "贵": "đắt, quý",
    "过": "qua, đã (trợ từ)",
    "还": "còn, vẫn",
    "孩子": "con, trẻ con",
    "好吃": "ngon",
    "黑": "đen",
    "红": "đỏ",
    "欢迎": "chào mừng, hoan nghênh",
    "回答": "trả lời",
    "机场": "sân bay",
    "鸡蛋": "trứng gà",
    "件": "cái (lượng từ)",
    "教室": "phòng học, lớp học",
    "姐姐": "chị gái",
    "介绍": "giới thiệu",
    "进": "vào",
    "近": "gần",
    "就": "liền, ngay",
    "觉得": "cảm thấy, cho rằng",
    "咖啡": "cà phê",
    "开始": "bắt đầu",
    "考试": "thi, kiểm tra",
    "可能": "có thể, có lẽ",
    "可以": "có thể, được",
    "课": "bài, tiết học",
    "快": "nhanh",
    "快乐": "vui vẻ, hạnh phúc",
    "累": "mệt",
    "离": "cách, rời",
    "两": "hai (đi kèm lượng từ)",
    "路": "đường",
    "旅游": "du lịch",
    "卖": "bán",
    "慢": "chậm",
    "忙": "bận",
    "每": "mỗi",
    "妹妹": "em gái",
    "门": "cửa",
    "面条": "mì, phở",
    "男": "nam, con trai",
    "您": "ngài, ông/bà (kính ngữ)",
    "牛奶": "sữa bò",
    "女": "nữ, con gái",
    "旁边": "bên cạnh",
    "跑步": "chạy bộ",
    "便宜": "rẻ",
    "票": "vé",
    "妻子": "vợ",
    "起床": "thức dậy",
    "千": "nghìn, ngàn",
    "铅笔": "bút chì",
    "晴": "trời nắng, trời quang",
    "去年": "năm ngoái",
    "让": "cho phép, để",
    "日": "ngày, mặt trời",
    "上班": "đi làm",
    "身体": "cơ thể, sức khỏe",
    "生病": "bị ốm, bị bệnh",
    "生日": "sinh nhật",
    "时间": "thời gian",
    "事情": "việc, chuyện",
    "手表": "đồng hồ đeo tay",
    "手机": "điện thoại di động",
    "说话": "nói chuyện",
    "送": "tặng, đưa tiễn",
    "虽然": "mặc dù, tuy",
    "但是": "nhưng, nhưng mà",
    "它": "nó (chỉ vật)",
    "题": "đề, câu hỏi",
    "踢足球": "đá bóng",
    "跳舞": "nhảy, khiêu vũ",
    "外": "ngoài",
    "完": "xong, hết",
    "玩": "chơi",
    "晚上": "buổi tối",
    "往": "về phía, hướng tới",
    "为什么": "tại sao, vì sao",
    "问": "hỏi",
    "问题": "câu hỏi, vấn đề",
    "西瓜": "dưa hấu",
    "希望": "hy vọng, mong muốn",
    "洗": "rửa, giặt",
    "小时": "giờ (đơn vị thời gian)",
    "笑": "cười",
    "新": "mới",
    "姓": "họ",
    "休息": "nghỉ ngơi",
    "雪": "tuyết",
    "颜色": "màu sắc",
    "眼睛": "mắt, đôi mắt",
    "羊肉": "thịt cừu",
    "药": "thuốc",
    "要": "muốn, cần",
    "也": "cũng",
    "已经": "đã, rồi",
    "一起": "cùng nhau",
    "一下": "một chút",
    "因为": "vì, bởi vì",
    "所以": "cho nên, nên",
    "阴": "âm u, trời râm",
    "游泳": "bơi, bơi lội",
    "右边": "bên phải",
    "鱼": "cá",
    "远": "xa",
    "运动": "vận động, thể thao",
    "再": "lại, nữa",
    "早上": "buổi sáng sớm",
    "丈夫": "chồng",
    "找": "tìm",
    "着": "đang (trợ từ tiếp diễn)",
    "真": "thật, thực sự",
    "正在": "đang (chỉ hành động đang diễn ra)",
    "知道": "biết",
    "准备": "chuẩn bị",
    "走": "đi bộ",
    "最": "nhất",
    "左边": "bên trái",

    # ═══════════════ HSK 3 ═══════════════
    "啊": "a, ơi! (thán từ)",
    "矮": "thấp, lùn",
    "爱好": "sở thích",
    "安静": "yên tĩnh",
    "把": "cầm; (giới từ đặt tân ngữ trước)",
    "班": "lớp, ca",
    "搬": "dọn, chuyển",
    "办法": "cách, phương pháp",
    "办公室": "văn phòng",
    "半": "nửa",
    "帮忙": "giúp đỡ",
    "包": "túi, bao",
    "饱": "no",
    "北方": "phương Bắc",
    "被": "bị, được (bị động)",
    "鼻子": "mũi",
    "比较": "so sánh, khá",
    "比赛": "thi đấu, cuộc thi",
    "笔记本": "sổ tay, laptop",
    "必须": "phải, bắt buộc",
    "变化": "thay đổi, biến hóa",
    "别人": "người khác",
    "冰箱": "tủ lạnh",
    "不但": "không những",
    "而且": "mà còn",
    "不过": "nhưng, tuy nhiên",
    "才": "mới (chỉ thời gian muộn)",
    "菜单": "thực đơn",
    "参加": "tham gia",
    "草": "cỏ",
    "层": "tầng, lớp",
    "差": "kém, thiếu",
    "超市": "siêu thị",
    "衬衫": "áo sơ mi",
    "成绩": "thành tích, điểm số",
    "城市": "thành phố",
    "迟到": "đến muộn, trễ",
    "除了": "ngoài, trừ",
    "厨房": "nhà bếp",
    "春": "mùa xuân",
    "词语": "từ ngữ",
    "聪明": "thông minh",
    "打扫": "quét dọn, lau dọn",
    "打算": "dự định, dự tính",
    "带": "mang, đeo",
    "担心": "lo lắng",
    "蛋糕": "bánh kem, bánh ngọt",
    "当然": "đương nhiên, tất nhiên",
    "地": "đất; (trợ từ trạng ngữ)",
    "地方": "nơi, địa điểm",
    "地铁": "tàu điện ngầm",
    "地图": "bản đồ",
    "电梯": "thang máy",
    "电子邮件": "email, thư điện tử",
    "东": "đông, phía đông",
    "冬": "mùa đông",
    "动物": "động vật, con vật",
    "短": "ngắn",
    "段": "đoạn",
    "锻炼": "tập luyện, rèn luyện",
    "多么": "biết bao, lắm",
    "饿": "đói",
    "耳朵": "tai",
    "发": "gửi, phát",
    "发烧": "sốt",
    "发现": "phát hiện",
    "方便": "tiện lợi, thuận tiện",
    "放": "đặt, để, thả",
    "放心": "yên tâm",
    "分": "phút; phân, chia",
    "附近": "gần đây, phụ cận",
    "复习": "ôn tập",
    "干净": "sạch sẽ",
    "敢": "dám",
    "感冒": "cảm cúm",
    "感兴趣": "hứng thú, quan tâm",
    "刚才": "vừa nãy, lúc nãy",
    "根据": "căn cứ, theo",
    "跟": "với, theo",
    "更": "càng, hơn",
    "公园": "công viên",
    "故事": "câu chuyện",
    "刮风": "gió thổi",
    "关": "đóng, tắt",
    "关心": "quan tâm",
    "关于": "về, liên quan đến",
    "国家": "quốc gia, đất nước",
    "果汁": "nước ép trái cây",
    "过去": "quá khứ, đi qua",
    "还是": "hay là, vẫn",
    "害怕": "sợ hãi",
    "黄河": "Hoàng Hà",
    "护照": "hộ chiếu",
    "花": "hoa; tiêu (tiền)",
    "花园": "vườn hoa",
    "画": "vẽ, bức tranh",
    "坏": "hỏng, xấu",
    "换": "đổi, thay",
    "环境": "môi trường",
    "黄": "vàng",
    "回忆": "hồi ức, nhớ lại",
    "会议": "cuộc họp, hội nghị",
    "或者": "hoặc, hay là",
    "几乎": "gần như, hầu như",
    "机会": "cơ hội",
    "极": "cực kì, vô cùng",
    "记得": "nhớ",
    "季节": "mùa",
    "检查": "kiểm tra",
    "简单": "đơn giản",
    "健康": "khỏe mạnh, sức khỏe",
    "讲": "giảng, nói",
    "教": "dạy",
    "角": "góc, hào (tiền)",
    "脚": "chân, bàn chân",
    "接": "đón, nhận",
    "街道": "đường phố",
    "节目": "chương trình",
    "节日": "ngày lễ, lễ hội",
    "结婚": "kết hôn",
    "结束": "kết thúc",
    "解决": "giải quyết",
    "借": "mượn, cho mượn",
    "经常": "thường xuyên",
    "经过": "đi qua, trải qua",
    "经理": "giám đốc, quản lý",
    "久": "lâu",
    "旧": "cũ",
    "句子": "câu (ngữ pháp)",
    "决定": "quyết định",
    "渴": "khát",

    # ═══════════════ HSK 4 ═══════════════
    "爱情": "tình yêu",
    "安排": "sắp xếp",
    "安全": "an toàn",
    "按时": "đúng giờ",
    "按照": "theo, chiếu theo",
    "抱歉": "xin lỗi, thật có lỗi",
    "保护": "bảo vệ",
    "保证": "bảo đảm, cam đoan",
    "报名": "đăng ký",
    "倍": "lần, gấp",
    "本来": "vốn dĩ, ban đầu",
    "笨": "ngu, chậm hiểu",
    "比如": "ví dụ như",
    "毕业": "tốt nghiệp",
    "遍": "lượt, lần",
    "标准": "tiêu chuẩn",
    "表格": "bảng biểu, mẫu đơn",
    "表示": "biểu thị, bày tỏ",
    "表演": "biểu diễn",
    "表扬": "khen ngợi, biểu dương",
    "饼干": "bánh quy",
    "并且": "hơn nữa, và",
    "博士": "tiến sĩ",
    "不仅": "không chỉ",
    "不管": "bất kể, bất luận",
    "部分": "bộ phận, phần",
    "擦": "lau, chùi",
    "猜": "đoán",
    "材料": "vật liệu, tài liệu",
    "参观": "tham quan",
    "餐厅": "nhà ăn, nhà hàng",
    "厕所": "nhà vệ sinh",
    "差不多": "gần giống, tương tự",
    "尝": "nếm, thử",
    "场": "sân; trận (lượng từ)",
    "长城": "Vạn Lý Trường Thành",
    "长江": "sông Trường Giang",
    "超过": "vượt quá",
    "吵": "ồn ào, cãi nhau",
    "成功": "thành công",
    "成为": "trở thành",
    "诚实": "thật thà, thành thực",
    "乘坐": "đi, ngồi (phương tiện)",
    "程度": "mức độ, trình độ",
    "吃惊": "ngạc nhiên, kinh ngạc",
    "重新": "làm lại, từ đầu",
    "抽烟": "hút thuốc",
    "出差": "đi công tác",
    "出发": "xuất phát, lên đường",
    "出生": "sinh ra",
    "出现": "xuất hiện",
    "传真": "fax",
    "窗户": "cửa sổ",
    "词典": "từ điển",
    "从来": "từ trước đến nay",
    "粗心": "bất cẩn, sơ ý",
    "存": "gửi, lưu, tiết kiệm",
    "错误": "sai lầm, lỗi",
    "答案": "đáp án",
    "打扮": "trang điểm, ăn mặc",
    "打扰": "làm phiền, quấy rầy",
    "打印": "in ấn",
    "打折": "giảm giá",
    "大概": "đại khái, khoảng",
    "大使馆": "đại sứ quán",
    "大约": "khoảng, ước chừng",
    "代替": "thay thế",
    "戴": "đeo, đội",
    "当": "khi, lúc, làm",
    "当时": "lúc đó, khi đó",
    "导游": "hướng dẫn viên",
    "倒": "đổ, rót; ngược lại",
    "到处": "khắp nơi",
    "到底": "rốt cuộc, cuối cùng",
    "道歉": "xin lỗi",
    "得意": "đắc ý, tự hào",
    "灯": "đèn",
    "登机牌": "thẻ lên máy bay",
    "底": "đáy, dưới cùng",
    "地址": "địa chỉ",
    "地球": "trái đất, địa cầu",
    "调查": "điều tra",
    "掉": "rơi, mất",
    "丢": "mất, đánh mất",
    "动作": "hành động, động tác",
    "堵车": "tắc đường, kẹt xe",
    "肚子": "bụng",
    "短信": "tin nhắn",
    "对话": "đối thoại, hội thoại",
    "对面": "đối diện",
    "对于": "đối với",
    "顿": "bữa (lượng từ ăn uống)",
    "多余": "thừa, dư",
    "多云": "nhiều mây",
    "而": "mà, và",
    "儿童": "trẻ em, nhi đồng",
    "发生": "xảy ra, phát sinh",
    "发展": "phát triển",
    "法律": "pháp luật",
    "翻译": "dịch, phiên dịch",
    "烦恼": "phiền não, bực bội",
    "反对": "phản đối",
    "反映": "phản ánh",
    "方法": "phương pháp, cách",
    "方面": "phương diện, mặt",
    "方向": "phương hướng, hướng",
    "房东": "chủ nhà",
    "放弃": "từ bỏ, bỏ cuộc",
    "放暑假": "nghỉ hè",
    "份": "phần (lượng từ)",
    "丰富": "phong phú",
    "否则": "nếu không thì",
    "符合": "phù hợp",
    "付款": "thanh toán, trả tiền",
    "复印": "photo, sao chép",
    "复杂": "phức tạp",
    "负责": "chịu trách nhiệm, phụ trách",
    "改变": "thay đổi",
    "干": "khô; làm",
    "感动": "cảm động",
    "感觉": "cảm giác, cảm nhận",
    "感情": "tình cảm",
    "感谢": "cảm tạ, cảm ơn",
    "赶": "kịp, đuổi theo",
    "刚": "vừa mới",
    "钢琴": "đàn piano",
    "高速公路": "đường cao tốc",
    "各": "mỗi, các",
    "工资": "tiền lương",
    "公里": "km, cây số",
    "功夫": "công phu, võ thuật",
    "共同": "chung, cùng nhau",
    "够": "đủ",
    "购物": "mua sắm",
    "估计": "ước tính, dự đoán",
    "鼓励": "khuyến khích, cổ vũ",
    "故意": "cố ý",
    "顾客": "khách hàng",
    "挂": "treo, mắc",
    "关键": "mấu chốt, then chốt",
    "观众": "khán giả",
    "管理": "quản lý",
    "光": "ánh sáng; chỉ, chỉ có",
    "广播": "phát thanh, quảng bá",
    "广告": "quảng cáo",
    "逛": "dạo, đi chơi",
    "规定": "quy định",
    "国际": "quốc tế",
    "国籍": "quốc tịch",
    "果然": "quả nhiên, đúng như dự đoán",

    # ═══════════════ HSK 5 ═══════════════
    "唉": "ôi, chao (thán từ)",
    "爱护": "yêu quý, gìn giữ",
    "爱惜": "quý tiếc, trân trọng",
    "爱心": "lòng yêu thương",
    "安慰": "an ủi",
    "暗": "tối, âm thầm",
    "熬夜": "thức khuya",
    "把握": "nắm chắc, nắm bắt",
    "摆": "bày, đặt",
    "办理": "xử lý, làm thủ tục",
    "傍晚": "chiều tối, xẩm tối",
    "包裹": "bưu kiện, gói",
    "包含": "bao gồm",
    "包括": "bao gồm, bao quát",
    "保持": "duy trì, giữ gìn",
    "保存": "bảo quản, lưu giữ",
    "保留": "bảo lưu, giữ lại",
    "保险": "bảo hiểm",
    "报到": "trình diện, báo danh",
    "报道": "đưa tin, bản tin",
    "报告": "báo cáo",
    "报社": "tòa soạn báo",
    "抱": "ôm",
    "抱怨": "phàn nàn, than phiền",
    "悲观": "bi quan",
    "背": "lưng; thuộc lòng",
    "背景": "bối cảnh, nền",
    "被子": "chăn, mền",
    "本科": "đại học (bậc cử nhân)",
    "本领": "bản lĩnh, tài năng",
    "本质": "bản chất",
    "比例": "tỉ lệ",
    "彼此": "nhau, lẫn nhau",
    "必然": "tất yếu, chắc chắn",
    "必要": "cần thiết",
    "避免": "tránh, phòng tránh",
    "编辑": "biên tập",
    "鞭炮": "pháo, pháo nổ",
    "辩论": "tranh luận",
    "标点": "dấu câu",
    "标志": "biểu tượng, dấu hiệu",
    "表达": "biểu đạt, diễn đạt",
    "表面": "bề mặt, bề ngoài",
    "表明": "biểu minh, cho thấy",
    "表情": "biểu cảm, nét mặt",
    "表现": "biểu hiện, thể hiện",
    "别扭": "khó chịu, gượng gạo",
    "冰激凌": "kem",
    "病毒": "vi-rút",
    "玻璃": "thủy tinh, kính",
    "播放": "phát (nhạc/video)",
    "脖子": "cổ",
    "博物馆": "bảo tàng, viện bảo tàng",
    "不安": "bất an, lo lắng",
    "不必": "không cần, khỏi phải",
    "不断": "không ngừng, liên tục",
    "不好意思": "ngại, xấu hổ",
    "不见得": "chưa chắc",
    "不耐烦": "mất kiên nhẫn, sốt ruột",
    "不然": "nếu không thì",
    "不如": "không bằng",
    "不足": "không đủ, thiếu",
    "布": "vải",
    "步骤": "bước, trình tự",
    "部门": "bộ phận, phòng ban",
    "财产": "tài sản",
    "采访": "phỏng vấn",
    "采取": "áp dụng, thực hiện",
    "彩虹": "cầu vồng",
    "参考": "tham khảo",
    "参与": "tham dự, tham gia",
    "惭愧": "xấu hổ, hổ thẹn",
    "操场": "sân vận động, sân tập",
    "操心": "lo lắng, bận tâm",
    "册": "cuốn, quyển (lượng từ)",
    "测验": "kiểm tra, trắc nghiệm",
    "曾经": "từng, đã từng",
    "插": "cắm, chèn",
    "差别": "khác biệt, sai khác",
    "差距": "khoảng cách, chênh lệch",
    "拆": "tháo, phá",
    "产品": "sản phẩm",
    "产生": "phát sinh, tạo ra",
    "长途": "đường dài",
    "常识": "kiến thức phổ thông",
    "抄": "chép, sao chép",
    "超级": "siêu cấp, siêu",
    "朝": "về phía; triều đại",
    "朝代": "triều đại",
    "潮湿": "ẩm ướt",
    "吵架": "cãi nhau",
    "炒": "xào, chiên",
    "车库": "gara, nhà để xe",
    "车厢": "toa tàu",
    "彻底": "triệt để, hoàn toàn",
    "沉默": "im lặng",
    "趁": "nhân lúc, tranh thủ",
    "称": "gọi, xưng",
    "称赞": "khen ngợi, ca tụng",
    "成分": "thành phần",
    "成果": "thành quả, kết quả",
    "成就": "thành tựu",
    "成立": "thành lập",
    "成语": "thành ngữ",
    "成长": "trưởng thành, lớn lên",
    "承担": "đảm nhận, gánh chịu",
    "承认": "thừa nhận, công nhận",
    "承受": "chịu đựng",
    "程序": "trình tự, chương trình",
    "吃亏": "chịu thiệt, bị lỗ",
    "冲": "xông, lao, pha (nước)",
    "充电器": "sạc, cục sạc",
    "充分": "đầy đủ, sung mãn",
    "充满": "tràn đầy",
    "重复": "lặp lại, trùng lặp",
    "宠物": "thú cưng",
    "抽屉": "ngăn kéo",
    "抽象": "trừu tượng",
    "丑": "xấu xí",
    "臭": "hôi, thối",
    "出版": "xuất bản",
    "出口": "cửa ra, xuất khẩu",
    "出色": "xuất sắc, nổi bật",
    "出席": "tham dự, có mặt",
    "初级": "sơ cấp, bước đầu",
    "除夕": "đêm giao thừa",
    "处理": "xử lý",
    "传播": "truyền bá, lan truyền",
    "传染": "lây nhiễm",
    "传说": "truyền thuyết",
    "传统": "truyền thống",
    "窗帘": "rèm cửa",
    "闯": "xông vào, vượt",
    "创造": "sáng tạo, tạo ra",
    "吹": "thổi",
    "词汇": "từ vựng",
    "辞职": "từ chức, nghỉ việc",
    "此外": "ngoài ra",
    "刺激": "kích thích",
    "匆忙": "vội vàng, hấp tấp",
    "从此": "từ đó, từ nay",
    "从而": "từ đó mà",
    "从前": "ngày xưa, trước kia",
    "从事": "làm, theo đuổi",
    "粗糙": "thô ráp, sơ sài",
    "促进": "thúc đẩy, xúc tiến",
    "促使": "thúc giục, khiến cho",
    "醋": "giấm",
    "催": "giục, thúc giục",
    "存在": "tồn tại",
    "措施": "biện pháp",

    # ═══════════════ HSK 6 ═══════════════
    "哀悼": "thương tiếc, ai điếu",
    "爱不释手": "yêu không rời tay",
    "碍": "cản trở, ngăn cản",
    "安居乐业": "an cư lạc nghiệp",
    "安宁": "an ninh, yên bình",
    "安详": "an nhiên, bình thản",
    "暗示": "ám chỉ, gợi ý",
    "案件": "vụ án",
    "案例": "ví dụ thực tế, án lệ",
    "奥秘": "bí ẩn, huyền bí",
    "巴不得": "chỉ mong, khao khát",
    "白搭": "vô ích, vô dụng",
    "拜访": "thăm viếng, bái phỏng",
    "拜年": "chúc Tết",
    "败坏": "bại hoại, làm hỏng",
    "颁布": "ban bố, công bố",
    "颁发": "trao tặng, cấp",
    "班主任": "giáo viên chủ nhiệm",
    "搬迁": "di dời, chuyển đi",
    "板": "tấm ván, bảng",
    "版本": "phiên bản",
    "办事处": "văn phòng đại diện",
    "半途而废": "bỏ dở nửa chừng",
    "扮演": "đóng vai",
    "包庇": "bao che, dung túng",
    "包袱": "gánh nặng, túi bọc",
    "包围": "bao vây",
    "包装": "đóng gói, bao bì",
    "宝贝": "bảo bối, con yêu",
    "宝贵": "quý báu, quý giá",
    "保密": "bảo mật, giữ bí mật",
    "保姆": "bảo mẫu, giúp việc",
    "保守": "bảo thủ",
    "保卫": "bảo vệ",
    "保障": "bảo đảm, đảm bảo",
    "报仇": "trả thù, báo thù",
    "报酬": "thù lao, tiền công",
    "报答": "báo đáp, đền ơn",
    "报复": "báo thù, trả đũa",
    "报警": "báo cảnh sát",
    "报销": "thanh toán (chi phí), tiêu hủy",
    "抱负": "hoài bão, chí lớn",
    "暴力": "bạo lực",
    "暴露": "bộc lộ, phơi bày",
    "曝光": "phơi sáng, vạch trần",
    "爆炸": "nổ tung, bùng nổ",
    "悲哀": "bi ai, đau buồn",
    "卑鄙": "ti bỉ, hèn hạ",
    "北极": "Bắc Cực",
    "备份": "sao lưu, dự phòng",
    "备忘录": "bản ghi nhớ",
    "背叛": "phản bội",
    "背诵": "đọc thuộc lòng",
    "奔波": "bôn ba, vất vả",
    "奔驰": "lao nhanh, phi nước đại",
    "本能": "bản năng",
    "本人": "bản thân, đích thân",
    "本身": "bản thân, tự thân",
    "本事": "tài năng, bản sự",
    "笨拙": "vụng về, lóng ngóng",
    "逼迫": "ép buộc, bức bách",
    "鼻涕": "nước mũi",
    "比方": "ví dụ",
    "比喻": "so ví, ẩn dụ",
    "比重": "tỉ trọng",
    "彼岸": "bờ bên kia, bỉ ngạn",
    "必定": "chắc chắn, nhất định",
    "必经之路": "con đường tất yếu",
    "闭塞": "bế tắc, khép kín",
    "弊端": "tệ nạn, khuyết điểm",
    "边疆": "biên cương, biên giới",
    "边缘": "rìa, bên lề",
    "编织": "dệt, đan",
    "鞭策": "thúc đẩy, roi vọt",
    "贬低": "hạ thấp, coi nhẹ",
    "贬义": "nghĩa xấu, nghĩa tiêu cực",
    "便利": "tiện lợi",
    "辨别": "phân biệt, nhận biết",
    "辨认": "nhận ra, nhận dạng",
    "辩护": "biện hộ, bào chữa",
    "辩解": "biện bạch, cãi lại",
    "辩证": "biện chứng",
    "标本": "mẫu vật, tiêu bản",
    "标记": "đánh dấu, ký hiệu",
    "标题": "tiêu đề",
    "表决": "biểu quyết",
    "表态": "bày tỏ thái độ",
    "憋": "nín nhịn, bức bách",
    "别墅": "biệt thự",
    "濒临": "bên bờ, sắp (tuyệt chủng)",
    "冰雹": "mưa đá",
    "并非": "không phải",
    "并列": "song song, ngang hàng",
    "波浪": "sóng",
    "波涛": "sóng to, ba đào",
    "驳斥": "bác bỏ, phản bác",
    "博大精深": "sâu rộng uyên bác",
    "博览会": "hội chợ triển lãm",
    "薄弱": "yếu ớt, mỏng manh",
    "补偿": "bồi thường, bù đắp",
    "补充": "bổ sung",
    "补救": "bù đắp, cứu vãn",
    "补贴": "phụ cấp, trợ cấp",
    "不惜": "không tiếc",
    "不相上下": "ngang ngửa, bất phân thắng bại",
    "不言而喻": "không cần nói cũng hiểu",
    "不由得": "không thể không, bất giác",
    "不择手段": "bất chấp thủ đoạn",
    "布局": "bố cục, sắp đặt",
    "布置": "bài trí, sắp xếp",
    "步伐": "bước đi, nhịp bước",
    "部署": "bố trí, triển khai",
    "部位": "bộ phận, vị trí",
    "裁缝": "thợ may",
    "裁判": "trọng tài",
    "裁员": "cắt giảm nhân viên",
    "财富": "tài sản, của cải",
    "采购": "mua sắm, thu mua",
    "采集": "thu thập, hái lượm",
    "采纳": "chấp nhận, tiếp thu",
    "彩票": "vé số, xổ số",
    "参照": "tham chiếu, đối chiếu",
    "惨": "thảm, thê thảm",
    "灿烂": "rực rỡ, xán lạn",
    "仓促": "vội vã, gấp gáp",
    "仓库": "kho, nhà kho",
    "舱": "khoang (tàu, máy bay)",
    "操劳": "lao lực, vất vả",
    "操练": "huấn luyện, tập luyện",
    "操纵": "thao túng, điều khiển",
    "草案": "bản thảo, dự thảo",
    "草率": "qua loa, cẩu thả",
    "侧面": "mặt bên, khía cạnh",
    "策划": "lên kế hoạch, sách hoạch",
    "策略": "chiến lược, sách lược",
    "测量": "đo đạc, đo lường",
    "层出不穷": "liên tiếp xuất hiện",
    "层次": "tầng bậc, cấp bậc",
    "差异": "khác biệt, sai khác",
    "拆除": "phá bỏ, tháo dỡ",
    "拆迁": "giải tỏa, di dời",
    "搀": "dìu, đỡ",
    "产业": "ngành nghề, sản nghiệp",
    "颤抖": "run rẩy, rung",
    "猖狂": "cuồng loạn, hung hãn",
    "尝试": "thử, cố gắng",
    "常务": "thường vụ, thường trực",
}
